#!/usr/bin/env bash
# Generates the secrets for the database step: strong random passwords for sa, seclab_app and seclab_migrator, a self-signed
# TLS certificate for the SQL Server container, and the two connection strings. Everything goes into .env and certs/ (both git-ignored).
#
#   bash docs/init-secrets.sh            # refuses to overwrite an existing .env
#   bash docs/init-secrets.sh --force    # new passwords and a new certificate (then re-create the container: docker compose down -v)
#
# Use the result:  set -a; source .env; set +a      (docker compose reads .env by itself)
set -euo pipefail
cd "$(dirname "$0")/.."
[ -f .env ] && [ "${1:-}" != "--force" ] && { echo ".env already exists (use --force to replace it)"; exit 1; }
command -v openssl >/dev/null || { echo "openssl is required"; exit 1; }

# 32 characters from a CSPRNG; letters and digits only so the value is safe in a connection string, in sqlcmd and in a shell.
# Retry until all three character classes that SQL Server's password policy asks for are present.
pw() {
  while :; do
    p=$(openssl rand -base64 64 | tr -dc 'A-Za-z0-9' | head -c 32)
    [[ $p =~ [A-Z] && $p =~ [a-z] && $p =~ [0-9] && ${#p} -eq 32 ]] && { echo "$p"; return; }
  done
}
SA=$(pw); APP=$(pw); MIG=$(pw)

# A certificate for "localhost" that the client can pin: the server proves who it is, the traffic is encrypted, nothing is "trusted blindly".
mkdir -p certs/sql
openssl req -x509 -newkey rsa:2048 -nodes -days 825 -subj "/CN=localhost" -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" \
  -keyout certs/sql/server.key -out certs/sql/server.crt 2>/dev/null
chmod 644 certs/sql/server.crt
chmod 644 certs/sql/server.key   # lab only: the container user (uid 10001) must read the bind-mounted key. Production: a CA-issued certificate, key in a vault/HSM.
CERT="$PWD/certs/sql/server.crt"

TLS="Encrypt=True;TrustServerCertificate=False;ServerCertificate=$CERT"
umask 077
cat > .env <<ENV
# Generated by docs/init-secrets.sh - never commit this file.
MSSQL_SA_PASSWORD=$SA
SECLAB_APP_PASSWORD=$APP
SECLAB_MIGRATOR_PASSWORD=$MIG
ConnectionStrings__Default='Server=localhost,1433;Database=SecLab;User Id=seclab_app;Password=$APP;$TLS'
ConnectionStrings__Migrator='Server=localhost,1433;Database=SecLab;User Id=seclab_migrator;Password=$MIG;$TLS'
ENV
echo "Wrote .env and certs/sql/. Load it:  set -a; source .env; set +a"
